### PR TITLE
Add Widefield segmentation data for blue and violet channels

### PR DESCRIPTION
**Pull request by weiglszonja**
Add segmentation data for the Widefield imaging session

- `PlaneSegmentationProcessedBlue` contains the ROIs (centroids and labels) and the image_masks for the downsampled imaging (blue channel) links to `ImagingPlaneBlue`
- `SegmentationImagesBlue` contains the manual mask and the contrast based vasculature mask for the blue channel in the full size session image. (1024 x 1024)
- `SegmentationImagesProcessedBlue` contains the contrast based vasculature and the pca mask for the blue channel in the binned image.  (128 x 128)
- `SegmentationImagesProcessedViolet` contains the pca mask for the violet channel in the binned image.  (128 x 128)

### CODE REVIEW

**Comment by weiglszonja** [comment]
Stub file on s3 is at `pinto-lab-to-nwb/new_stub_DrChicken_20230419_20hz.nwb`

**Comment by CodyCBakerPhD** [comment]
Everything looks good except for the processed 1P series (in discussion, not sure why this was getting set in this way) is currently float64 but should be uint16? Possibly something to do with how the numpy array is pre-allocated?

**Comment by weiglszonja** [comment]
For the processed 1P, the `dtype` of video is determined from the `dtype` from `DatasetView` as we read the mat file in, which is `float64` 
```python
self._video = DatasetView(file[expected_struct_name])```

But I also checked for the raw 1P, and that should be `float16` which is `float64` right now, but that should be an easy fix in roiextractors (and this one is because of creating a pre-allocated array without specifying the data type, which defaults to float64)

**Comment by CodyCBakerPhD** [comment]
@weiglszonja OK let me know when there's a new file to check and this should be good

**Comment by weiglszonja** [comment]
@CodyCBakerPhD Thanks, this change should be reflected at [new_stub_DrChicken_20230419_20hz.nwb](https://s3.console.aws.amazon.com/s3/object/catalystneuro-processing?region=us-east-2&prefix=pinto-lab-to-nwb/new_stub_DrChicken_20230419_20hz.nwb)

**Comment by CodyCBakerPhD** [comment]
@weiglszonja It looks like the same neurodata objects still have the same `float64` data type in the new file

**Comment by weiglszonja** [comment]
For the raw they show up as `uint16` for me as here:
Screenshot 2023-11-15 at 16 21 16

**Comment by CodyCBakerPhD** [comment]
@weiglszonja Sorry for not being clear with which data set I'm talking about

image

**Comment by weiglszonja** [comment]
TODO:
as per our meeting add dtype at init for processed imaging interface, which will either keep the float64 if they request or cast it to int16 by default

**Comment by weiglszonja** [comment]
updated file: [DrChicken_20230419_20hz.nwb](https://s3.console.aws.amazon.com/s3/object/catalystneuro-processing?region=us-east-2&prefix=pinto-lab-to-nwb/DrChicken_20230419_20hz.nwb)

**Comment by CodyCBakerPhD** [comment]
Yep, that looks great now!

**Review by CodyCBakerPhD — APPROVED** [review]

**Pull request merged**
