### PR TITLE
Add Widefield Imaging (raw and processed) for Blue and Violet channels

### PR DESCRIPTION
**Pull request by weiglszonja**
The Widefield imaging data consists of:

Raw Imaging
- Micro-Manager ome-tif format (image size: 1024, 1024)
- Has blue and violet frames 

Downsampled Imaging
- .mat file (image size: 128, 128)
- Has blue and violet frames

Strobe sequence
- strobe sequence data (values are 1 or 2): tells us the order of blue and violet frames
- 1 corresponds to blue frame
- 2 corresponds to violet frame

Since for segmentation they only consider the blue frames, we are saving `OnePhotonSeries` data for each channel.
The extractors should read the raw and processed data, and based on the strobe sequence they should subset the frames depending on which channel they are loading.

### CODE REVIEW

**Comment by weiglszonja** [comment]
Test file with 200 frames is named `stub_TS12_20220407_20hz_noteasy_1`.nwb

**Comment by weiglszonja** [comment]
We will receive a more recent example session, once we have that I will update the prototype file and mark this ready for review.

**Comment by weiglszonja** [comment]
Current stub on s3 is at: `pinto-lab-to-nwb/stub_DrChicken_20230419_20hz.nwb`

**Comment by CodyCBakerPhD** [comment]
LGTM!

**Review by CodyCBakerPhD — APPROVED** [review]

**Pull request merged**
